### ISSUE TITLE
.uge File format description ?

### ISSUE THREAD

**Issue by sttng** [SuperDisk/UGE#102]
Is there a file format description of the .uge (and possibly also of the instrument export format) available ?

**Comment by SuperDisk** [comment]
Right now, the only description of the format is the source code in `song.pas`. I know that's not a great answer. I'm planning on documenting the format soon in a reworking of the documentation.

**Comment by SuperDisk** [comment]
In the meantime, Valen wrote a spec which will be integrated into the docs soon. You can read it [here.](https://github.com/datguywitha3ds/Valens-Game-Boy-Graveyard/blob/main/UGE-Format.md)

**Comment by SuperDisk** [comment]
The spec has been integrated into [the new docs.](https://eldred.fr/hUGETracker/)
