### ISSUE TITLE
hUGETracker + Compression + GBDK

### ISSUE THREAD

**Issue by bbbbbr** [SuperDisk/UGE#105]
Just documenting some of how to get it working with GBDK in case it's useful for others. (Is there a better place for this?)

(Thanks to superdisk for making this special version & sharing it with the rest of us!)

### hUGETracker / Driver with compression support + GBDK-2020 (4.1.0, but others too)
Very useful for 32K Carts!

1. hUGETracker Editor build (1.0 b.9 based)
    - ~~https://github.com/SuperDisk/hUGETracker/actions/runs/3010801289~~
    - ~~https://github.com/SuperDisk/hUGETracker/actions/runs/5051027676~~
    - https://github.com/SuperDisk/hUGETracker/actions/runs/9062640752 (Linux only)

2. hUGETracker Driver (1.0 b.9 based)
    - https://github.com/SuperDisk/hUGEDriver/tree/uncap

3. Build with RGBDS 0.5.2
    - https://github.com/gbdev/rgbds/releases/tag/v0.5.2

4. Use rgb2sdas from hUGETracker 1.0 b10 release build
    - https://github.com/SuperDisk/hUGETracker/releases/tag/1.0b10

5. Build RGBDS (on Linux, at least)
```
~/rgbds/0.5.2
make
```

6. Build driver and convert to sdcc compatible object file
    - Use the `rgb2sdas.exe` from the b10 windows release, not from b9 or uncap.b9
```
cd gbdk_example
~/rgbds/0.5.2/rgbasm -DGBDK -ohUGEDriver.obj -i.. ../hUGEDriver.asm
chmod a+x rgb2sdas.exe
./rgb2sdas.exe hUGEDriver.obj
```

7. If needed, make it compatible with GBDK-2020 4.1.0 / new SDCC port/platform (2022)
    - Edit the resulting .o file and replace `-mgbz80` with `-msm83`

**Comment by SuperDisk** [comment]
Thanks for this information, it's very useful. I'll integrate something like this into the docs although what I need to do properly is rebase the compression changes on the latest driver, and update rgb2sdas.

**Comment by bbbbbr** [comment]
For `rgb2sdas` it might be useful to have a flag to select `sm83` or `gbz80` for the port when writing the object file.

In the future when gbdk 4.1.0 is established and part of GBStudio I can see `sm83` being an easy default, but for right now I'm not sure.

**Comment by SuperDisk** [comment]
This is an informative bit of information, but it probably doesn't belong in the issue tracker. Since it seems you've got this information up at [your repo](https://github.com/bbbbbr/hUGEDriver), I'm going to close this for now. If there's something you want me to do, please re-open. Thanks for compiling all the instructions in one place! I really do need to find a better compression solution though than this LZSS thing, this definitely isn't the optimal method :)

**Comment by bbbbbr** [comment]
Yeah, sounds good :+1:
