### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by sttng** [SuperDisk/UGE#108]
1) Suggest merging the comments tab into the General Tab, meaning the comments text field can just be a text field within the General Tab

2) Suggest changing the currently horizontal tab arrangement (General, Pattern, ...) into a vertical tab arrangement and move this to the right. This would free up some screen estate at the top so you can show more patterns in the pattern view.

**Comment by SuperDisk** [comment]
I'm going to leave (1) as is but I just implemented (2) in [9e31f80](https://github.com/SuperDisk/hUGETracker/commit/9e31f807ba7dde5b502e36d58f4e027b9e42571f).
