### ISSUE TITLE
Windows EXE on Mac via CrossOver: Popping Audio

### ISSUE THREAD

**Issue by tadashibashi** [SuperDisk/UGE#109]
Hello, like the title suggests, I'm running the Windows version of hUGETracker on Mac using CrossOver.
One big issue I'm encountering is popping audio, from what I believe might be from a small buffer size.
On FamiTracker, I'm able to increase the buffer size in the options menu and this problem goes away. Is there a possibility this option might make its way into hUGETracker as well?

Thanks for your time and consideration.

**Comment by SuperDisk** [comment]
HT natively supports Mac now with v1.0.4, so CrossOver shouldn't be necessary any more-- I also bumped up the audio buffer size. I should probably make it configurable but I hope this addresses your issue for now.

**Comment by tadashibashi** [comment]
Yes, thanks a lot, I just ran it on an M1 Mac on Sonoma 14.1.2 and there's no popping while running the demo songs. This definitely seems to have resolved the issue.
