### ISSUE TITLE
How do you change the song length?

### ISSUE THREAD

**Issue by Anonymous941** [SuperDisk/UGE#112]
I have a song that I would like to reduce the total length of.  I've read the entire manual twice, checked every single UI element several times, and I still can't figure this out.

**Comment by SuperDisk** [comment]
What do you mean by "reduce the total length of"? If you mean to end a pattern early, you can use the `D01` command to skip to the next pattern. If you mean you want to remove rows from the order table, you can right click to delete them.

**Comment by Anonymous941** [comment]
I mean that I have a looping song that I imported, and it has 63 rows.  I would like to trim part of the end of a song but can't seem to do that.

**Comment by SuperDisk** [comment]
I would recommend using D01 on whatever row you want to trim it at.

**Comment by Anonymous941** [comment]
Thank you, that solved it.
