### ISSUE TITLE
Subpattern jump command ignored at row 1F

### ISSUE THREAD

**Issue by coffeevalenbat** [SuperDisk/UGE#113]
So I'm trying to make instruments in Beta 10 and I noticed that the jump command seems to be ignored if placed on the last row, here, this instrument *should* jump back to row 16 (17 cus plus 1), but instead it's ignored and it jumps back to row 0, if I place the jump command on row 1E instead it works as intended, but I feel like this is a big enough issue to report, since there might be moments where I can't move the jump command one row up.
![image](https://user-images.githubusercontent.com/34352018/216371568-71cda62d-6c8e-4fbd-8534-dbe08337b47c.png)

**Comment by SuperDisk** [comment]
Found the issue, it was a bug in how the instrument preview rendered subpatterns for playback. That's what I get for trying to be slick and avoid shelling out to `rgbasm`. Fixed in 3550f4254774ea1fa91c3e35ec1cc7a01134dfc3, will merge into master soon, fix a few more bugs and put out a new release.
