### ISSUE TITLE
Killing subpattern instrument doesn't work if extra envelopes are used

### ISSUE THREAD

**Issue by coffeevalenbat** [SuperDisk/UGE#115]
If my subpattern instrument does any calls to CXY after I try to kill a subpattern instrument (IE, with C00 or E00), it comes back once the subpattern's CXY effect is called, in this case I gotta loop through a C03 to continue the vibrato while also lowering the wave channel volume, but if I call E00 from the pattern order, it comes back, Exx could implement a feature to stop a subpattern after it's called, I could also use the highest instrument as a "kill" instrument but that's sacrificing one instrument slot :/
![image](https://user-images.githubusercontent.com/34352018/216411208-c6f22e2d-31a0-4a75-927f-4784844668f6.png)

**Comment by SuperDisk** [comment]
If you want to stop a subpattern after it starts, use a jump command that jumps to its own row, which effectively halts it. Does that address your problem? Alternatively you could use `Axy` to volume slide towards zero instead of using `Cxy`.

**Comment by coffeevalenbat** [comment]
I tried using Axy but it seems to kill the wave channel almost instantly, and I'm using the loop to have vibrato as it fades so having a self loop would get rid of that vibrato, I can def get around it with some rearranging but it'd still be nice to be able to kill a subpattern instrument without tricks

**Comment by SuperDisk** [comment]
I mean why not just use E00 or whatever and then put a self-Jxx to its own row? That would effectively halt the subpattern which seems to be what you want.

**Comment by SuperDisk** [comment]
I think using self-jump and `E00` solves this, please reopen and let me know if that's not the case.
