### ISSUE TITLE
Instant crash when right clicking near the channel bar in the pattern tab

### ISSUE THREAD

**Issue by coffeevalenbat** [SuperDisk/UGE#117]
I realized that if you right click on the right spot alongside the noise channel on the pattern tab (which can happen a lot if you're not careful), the player mutes all channels before spitting out a crash error and closing the tracker. No idea what's going on.
![Animation](https://user-images.githubusercontent.com/34352018/216795425-c8f37474-9d33-44de-bae9-44178f56995f.gif)

**Comment by SuperDisk** [comment]
How embarrassing. Will fix, thanks!

**Comment by SuperDisk** [comment]
Amazingly, this problem has been around since [before the first ever release.](https://github.com/SuperDisk/hUGETracker/commit/37e79e4fc09fdad125229e79248710f5c3506989)

Fixed in [4e189dc](https://github.com/SuperDisk/hUGETracker/commit/4e189dc07b6d53b37ce0191a39d530d1a2197706), thanks.
