### ISSUE TITLE
GBS File export doesn't include timer-based values

### ISSUE THREAD

**Issue by coffeevalenbat** [SuperDisk/UGE#120]
The header file for GBS files still uses blank 0s for both timer based values, regardless of if the song uses timer based tempo or not, I tried modifying the header to add that back to the exported GBS file (Write timer divider to 0x0E and write 4 to 0x0F) and it works fine, so the fix should just be making hUGETracker replace those values during exporting.

**Comment by SuperDisk** [comment]
Fixed in 40f58c002d7c59dbd05f0df4269fb5d74f780c10. Thanks!
