### ISSUE TITLE
Displaying grid in waveform hand draw view

### ISSUE THREAD

**Issue by Kabcorp** [SuperDisk/UGE#122]
Is it possible to add a visible grid like the following picture?
The example is surely visually too aggressive but you get the idea.
Pixel dots could be enough.
![dots](https://user-images.githubusercontent.com/33150965/220198719-58f63b0c-cb67-4a1c-aa1f-f7b16761e42e.png)

**Comment by SuperDisk** [comment]
Implemented in bad74d4, thanks!
