### ISSUE TITLE
Program necessitates GLIBC_2.34

### ISSUE THREAD

**Issue by TheNailDev** [SuperDisk/UGE#123]
I am trying to run hUGETracker 1.0.0 on my Computer with Linux Mint 20.3, which only uses GLIBC 2.31
I get the following error message when running hUGETracker: ``/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./hUGETracker)``
Is there a specific reason for hUGETracker requiring GLIBC 2.34? In case there is no such reason, would it be possible to compile the application to use an older version of GLIBC for higher compatibility?

**Comment by ISSOtm** [comment]
hUGETracker's CI builds in Ubuntu 22, which has glibc 2.34; we could switch to Ubuntu 20, which has glibc 2.31 instead.

**Comment by SuperDisk** [comment]
This should be fixed in [e39ce29](https://github.com/SuperDisk/hUGETracker/commit/e39ce2925f5abefcfbfe5dd497ad81f0f17ed727), which downgrades Ubuntu. I'm also going to work towards putting out an AppImage which should hopefully address other dependencies (SDL).
