### ISSUE TITLE
dont default to including `include/*.inc`

### ISSUE THREAD

**Issue by zlago** [SuperDisk/UGE#125]
i would like to request exported songs to default to including `hUGE.inc` and requiring passing `-I include_path` to rgbasm instead of including `include/hUGE.inc`, as i neither want to change it after each export, nor am i willing to rename directories

hopefully thisll also work for gbdk

**Comment by SuperDisk** [comment]
Implemented in 4da1d2573d42be09e54d49bc9c286e44ca44b726, thanks.
