### ISSUE TITLE
"There was an error assembling the song for playback"

### ISSUE THREAD

**Issue by ThomasTheDustFurry** [SuperDisk/UGE#126]
I can't play the music, what do i do? I can't test the app
![image](https://user-images.githubusercontent.com/113155313/226146386-55070a0f-e4a7-437f-9d27-983e4c282a1e.png)

**Comment by ISSOtm** [comment]
If you aren't getting any output, it might be that RGBASM is failing to run at all.

Can you go into hUGETracker's directory, open a command prompt/PowerShell window (hold shift and right-click the directory), and then run `.\rgbasm.exe --version`?

**Comment by ThomasTheDustFurry** [comment]
[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Não
contém vírus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sáb., 1 de abr. de 2023 às 18:31, Eldred Habert ***@***.***>
escreveu:

**Comment by SuperDisk** [comment]
Hey Thomas. That image didn't go through, I think you need to post it on GitHub rather than email.

**Comment by SuperDisk** [comment]
I'm going to close this issue for now since I can't debug further, but just judging by the text in your issue comment, it might be due to Avast mistakenly marking `rgbasm` as a virus. Please re-open if you need more help as I'm happy to assist.
