### ISSUE TITLE
EInvalidCast with message Invalid Type Cast

### ISSUE THREAD

**Issue by DeerTears** [SuperDisk/UGE#129]
I'm keeping my believed reasoning for the bug out of the title in case it's not the case. Feel free to update the title as needed.

I got this crash after pasting from one pattern to another. Same channel (duty 2). It was a boundary select partway through the pattern, and it started on a Master Volume effect with no note attached.

Error message:
![photo_2023-06-18_10-11-34](https://github.com/SuperDisk/hUGETracker/assets/47726614/eb2a1b06-bd43-4a35-aa8d-6db3bf454220)

Backup created on error (zipped because Github doesn't trust .uge):
[BACKUP_{AE33236B-EDF2-43CE-917A-3C98FB547738}.zip](https://github.com/SuperDisk/hUGETracker/files/11782059/BACKUP_.AE33236B-EDF2-43CE-917A-3C98FB547738.zip)

The working file I was able to return to:
[triplet oneshot.zip](https://github.com/SuperDisk/hUGETracker/files/11782062/triplet.oneshot.zip)

I was able to finish my song at least, this only happened once, I haven't tried to deliberately reproduce it since.

**Comment by SuperDisk** [comment]
This should be fixed in [97fea04](https://github.com/SuperDisk/hUGETracker/commit/97fea04e5ee186a9b5e6220df786a3dfec8ed435), please re-open if it occurs again.
