### ISSUE TITLE
Importing a wave instrument into a square instrument slot glitch

### ISSUE THREAD

**Issue by nikku4211** [SuperDisk/UGE#147]
Here is the file with the glitch I'm reporting:
[HotayaGlitch.zip](https://github.com/SuperDisk/hUGETracker/files/12287194/HotayaGlitch.zip)

When I import a wave instrument into a square instrument slot, the instrument editor still treats the instrument as if it was for the wave channel.

This glitch remains even if I exit out of HUGETracker and open the file again.

It also causes HUGETracker to error out and be unable to play the song.

**Comment by SuperDisk** [comment]
Fixed in [ce24f3a](https://github.com/SuperDisk/hUGETracker/commit/ce24f3ab58720344d277e0c5c78bd5584139b25e).

Thanks for reporting!
