### ISSUE TITLE
Sample songs license

### ISSUE THREAD

**Issue by GValiente** [SuperDisk/UGE#148]
The license of those songs is public domain too?

**Comment by SuperDisk** [comment]
The sample songs are all arrangements by various artists, so they're not public domain. The source code is all public domain though.

**Comment by GValiente** [comment]
Do you know the license of any of those songs?

**Comment by GValiente** [comment]
It would be for including some of them in another library, giving proper credits to the authors and clarify their license.

**Comment by SuperDisk** [comment]
You'd probably need to track down the original artists if you're distributing their songs somewhere. The sample songs are a combination of original tracks by musicians who granted me permission to include them, and arrangements I did of existing tunes. Sorry I can't be of much help regarding the licenses.
