### ISSUE TITLE
Not Rendering .wav (after 1.0.4 update)

### ISSUE THREAD

**Issue by Rezrospect** [SuperDisk/UGE#151]
Trying to render a .wav from the program produces no temp files or final file. I tested with 1.0.0 and 1.0.3 just to make sure it wasn't my .uge file, and I also tried to use the sample songs. Uncertain if it may be an issue with my setup, though I can confirm previous versions are rendering properly. Not sure if there's some kind of log I can pull to help with this issue, but I'm happy to provide whatever else might assist.

Edit: Forgot to specify I'm using the Windows version on Windows 11.
Edit 2: All other export methods seem to work, so there's a chance it's a ffmpeg issue.

**Comment by SuperDisk** [comment]
Can you try invoking ffmpeg from the command line to see that it at least starts up? Sometimes antivirus programs prevent it from working (although it's odd if old HT versions work...). I'll take a look when I get home.

**Comment by Rezrospect** [comment]
Hmm, trying to run ffmpeg in the directory gives me an error that libiconv-2.dll is not found. Is this supposed to be in the directory? It does not appear to be present in previous versions, nor does it prevent functionality. Is it maybe the particular version of ffmpeg provided?
Edit: libwinpthread-1.dll and zlib1.dll were also not found. I have ffmpeg installed to path, though I don't know if this affects how the provided .exe is used or accessed. Hope this information is useful.

**Comment by Rezrospect** [comment]
OK! I decided to simply swap the ffmpeg.exe with the one provided in the previous version (1.0.3) and rendering works just fine. Perhaps the provided executable should just be swapped out (or perhaps there was a reason this was changed I'm unaware of?)

**Comment by SuperDisk** [comment]
It must be due to some of the changes introduced to the build process to make the Mac version work. Thanks for figuring it out, I'll fix soon.

**Comment by Rezrospect** [comment]
Best of luck! Thanks for the hard work!

**Comment by SuperDisk** [comment]
Fixed in [c8ae502](https://github.com/SuperDisk/hUGETracker/commit/c8ae502969b9f2caebeaec15d7b3db080fc6ce6f). Thanks for the report!
