### ISSUE TITLE
Microtuning support

### ISSUE THREAD

**Issue by nikolay-ulyanov** [SuperDisk/UGE#155]
Hi! Is it possible to add support for microtonal pitches/scales?

**Comment by SuperDisk** [comment]
You can modify the built in tuning table by editing this file: https://github.com/SuperDisk/hUGEDriver/blob/master/include/hUGE_note_table.inc

You can also kind of simulate off-pitched notes by putting `1xx` or `2xx` effects in subpatterns.

Anything beyond that isn't supported, sorry :(

**Comment by nikolay-ulyanov** [comment]
Oh cool, thanks; and what if I would create a game later in GBStudio - will this modification transfer to the rom file also?

**Comment by SuperDisk** [comment]
You'd have to create a GB Studio plugin which includes the modified pitch table, but it's doable.

**Comment by SuperDisk** [comment]
@nikolay-ulyanov If you're interested in learning more about how to potentially do this, please join the GB Studio discord or the hUGETracker discord, and we can talk about it more-- Coffee Bat has done the plugin thing already so we could possibly help you out.

**Comment by nikolay-ulyanov** [comment]
nice, thanks!
