### ISSUE TITLE
Drag Selection to move / retime pattern (Feature)

### ISSUE THREAD

**Issue by RichardULZ** [SuperDisk/UGE#16]
**Drag Selection Move**
From RichardULZ
> Click and drag a selection to move (cut paste) Like OpenMPT? Probably a feature request worth in itself. 

Since it's probably hard to program, i've split it off.

From @DeerTears Ember,
> personally..."drag selection to move" is my least-favourite program feature. I know this is a Windows text standard but I've always felt that text is too fine to let it work the way it wants to. It's just really inaccessible and I'd never want to count on it when there's young kids or anybody with fine-motor-difficulties who'd be unable to use it reliably.

I understand the inaccessibility concerns about drag to move for those with fine-motor-difficulties, but i argue it can make things more accessible, and if you've never used openMPT, the margin for movement is very lenient compared to text. 

To me it's an intuitive way to Re-time patterns, and more accessible than `Ctrl X` `Ctrl V` in many cases.
In OpenMPT, It is locked to the correct columns, dragging up/down is easy, left right needs bigger movements. The selection stays behind, while an outline of where it will place is shown.
Gif below.
![DragMove](https://user-images.githubusercontent.com/34431457/78309009-6489e100-75a6-11ea-842d-af1641e888a3.gif)

You are also able to hold Ctrl to copy instead of move, but strangely only after you start dragging, this makes it hard to copy tracks, so I still use Ctrl C for that.

**Comment by SuperDisk** [comment]
Implemented in a371c87. I know @DeerTears mentioned that this feature can be annoying to some users, so maybe a toggle in the settings should enable/disable it?
