### ISSUE TITLE
"Open manual" button leads to 404 error page

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [SuperDisk/UGE#163]
Hi. I downloaded the latest version of hUGETracker, but when I opened the manual, I was rewarded with a 404 error page, featuring Lakitu's sprite from _Mario Kart 64_. And when I brought up the Wayback Machine, it was indeed archived... partially, as subpages lead to an additional error from the Wayback Machine.

**Comment by SuperDisk** [comment]
Hey, I'm sorry about that. The manual used to be hosted there but is now here: https://superdisk.github.io/hUGETracker/

The code is updated to point to that new location but I just haven't put out a new release yet.... I really should, I'll do it now.

**Comment by SuperDisk** [comment]
Just released it: https://github.com/SuperDisk/hUGETracker/releases/tag/v1.0.8
