### ISSUE TITLE
Randomize...?

### ISSUE THREAD

**Issue by pixisdrywall** [SuperDisk/UGE#164]
The manual says that for the instruments, there's a "randomize" option. However, I don't have that. Nor do the images in the manual that specifically _say_ there's a randomize option. Please advise

**Comment by SuperDisk** [comment]
Ah, sorry about that. Randomize was a feature in an old, old version that got removed. I'll take it out of the manual.

**Comment by pixisdrywall** [comment]
Ah dang it, I suck at making instruments TT~TT Might not be the time to ask, but do you know anywhere I could find a free pack of premade instruments? (If not I'll just pick and choose some from the example songs)

**Comment by SuperDisk** [comment]
Picking and choosing from the sample songs is a valid method, I'd check out the ones by FADE since those show off the use of subpatterns. People can help you find/make instruments on the GB Studio discord if you want to come check that out as well.

**Comment by pixisdrywall** [comment]
Okay, thank you for your help!

**Comment by SuperDisk** [comment]
Resolved in da652fda7c791de047a165f26b80d180ca1b35a6
