### ISSUE TITLE
Crashes on start on Linux: EAccessViolation with message Access violation

### ISSUE THREAD

**Issue by cippaciong** [SuperDisk/UGE#165]
Hello,

I'm trying to run hUGETracker on Linux but it crashes on start with the following error:

```
An exception in hUGETracker has occured.
Your song has been backed up to /home/cippaciong/.cache/hUGETracker/BACKUP_{C99E121A-2BE4-4493-8460-85428FB46472}.uge, so don't worry!

Please report this issue on GitHub, or contact the maintainer directly via Discord or Email.

Email: <REDACTED>
Discord: <REDACTED>

The error is: EAccessViolation with message Access violation
```

I tried with `v1.0.8` and `v1.0.7` binaries downloaded from the GitHub release, as well as building from source using the AUR package for Archlinux (the build process is defined here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hugetracker#n65)

This is what I see in my terminal when I run `./hUGETracker`:
```sh
$ ./hUGETracker

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.628: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.628: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.628: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.628: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.628: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.629: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.629: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.629: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.629: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.629: Unable to locate theme engine in module_path: "murrine",

(hUGETracker:84055): Gtk-WARNING **: 17:47:23.629: Unable to locate theme engine in module_path: "murrine",
[FORMS.PP] ExceptionOccurred
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000454421
  $000000000044B7AD
  $0000000000453F84
  $000000000045C845
```

Please let me know if there's any additional information that I can provide 🙂

**Comment by SuperDisk** [comment]
I appreciate the details! Unfortunately I've heard of this problem before on Arch but haven't gotten the time to debug it. Will hopefully figure it out soon, but in the meanwhile the Windows version works with Wine. Sorry for the inconvenience.

**Comment by cippaciong** [comment]
Ah I see. Well, knowing that the problem is Arch specific it's already a good hint for further investigation.

If I can help you testing on Arch let me know and I'll do what I can 👍🏻 

Thanks a lot for developing hUGETracker and for its great documentation. I refer to it pretty often even if I'm mostly using GB Studio.

**Comment by SuperDisk** [comment]
I was able to replicate the issue in a Manjaro VM. It's a segfault when the LCL tries to determine the monitor's DPI. I'm not sure why that's happening, but I'll keep digging.

RE: the documentation, thanks :) @ISSOtm had a large part in that as well.

**Comment by SuperDisk** [comment]
@cippaciong I just pushed up a commit which might fix this. Since the AUR package pulls from git does it just mean you can update and try it out? If not, the binary will be here: https://github.com/SuperDisk/hUGETracker/actions/runs/9922737947

Please let me know if that works for you!

**Comment by ISSOtm** [comment]
The `hugetracker-git` package does pull from Git, but neither `hugetracker` nor `hugetracker-bin` will, FWIW. Thus, make sure to pick the first of those. (There's also a possibility that the binary from CI will exhibit a different behaviour from one compiled on your machine from the `PKGBUILD`, too..!)

**Comment by cippaciong** [comment]
Thanks guys, I can confirm that the latest version from git works fine now 👍🏻 

I have a couple of other minor problems, but I'll create separate issues for them and close this one.

Thanks again :)
