### ISSUE TITLE
Crash when instrument number entered

### ISSUE THREAD

**Issue by nekojanai** [SuperDisk/UGE#174]
https://github.com/user-attachments/assets/ffbe67b6-0b2e-41d9-a233-bc0e42f3cc4d

When an instrument number > what's available is entered into the pattern editor, the application crashes.

**Comment by SuperDisk** [comment]
Fixed in eafeffbb7ec1f47c4508df67945c219d4ff28e64. Thanks for reporting. It was a side effect of some "instrument highest value" optimization thing that I hadn't considered.
