### ISSUE TITLE
Export instruments as register values

### ISSUE THREAD

**Issue by basxto** [SuperDisk/UGE#20]
It would be nice if the actual register settings of instruments could be exported.
Just an info window, that shows how the registers will be set for instrument, would be sufficient too.

This would be mostly useful for using hUGETracker as an instrument designer for music/sound effects, that are run without the player. But it could also give some insight for hUGETracker users.

**Comment by SuperDisk** [comment]
This is possible, although there are 2 issues:
- The layout of the Gameboy registers splits the note frequency over 2 bytes... should these just be left blank so the user can mask in their own frequency?
- With the addition of noise macros, noise instruments are no longer just a single series of register writes-- should all of the macro values also be exported?

**Comment by basxto** [comment]
I think the notes should be laft blank since they are not part of the instrument itself?
Are macros with just one value possible?

**Comment by SuperDisk** [comment]
I'm closing this for now since noise macros render this sort of infeasible, and there are other tools which you can use to make SFX register writes.
