### ISSUE TITLE
[Feature Request] Numbered rows on the tracker

### ISSUE THREAD

**Issue by coderkei** [SuperDisk/UGE#21]
I would like to request a feature for labeling the individual rows in the tracker with a number, it can be useful to know exactly which part of the song you are in. The following is an example in OpenMPT of what I am requesting:

![image](https://i.imgur.com/Edb1Ylf.png)

Thank you!

**Comment by SuperDisk** [comment]
![image](https://user-images.githubusercontent.com/1688837/85937876-a12f5500-b8d5-11ea-9c90-2cb9d63f6886.png)

Implemented in dfbd736f292f68421a892f9ee8346a2157fa3698, thanks for reporting.
