### ISSUE TITLE
New keyboard shortcuts

### ISSUE THREAD

**Issue by Kabcorp** [SuperDisk/UGE#26]
4 unavoidable shortcuts:
-Play
-Play from cursor
-Pause
-Stop (& go to row 0)

Actually, we have to clic on the top buttons, it makes a lot of mouse move for basic features.

**Comment by SuperDisk** [comment]
This is implemented as Ctrl+enter, shift+enter, and enter. Pause isn't implemented but I don't think it's really necessary, just stop and play from cursor. Closing for now, please reopen if I misunderstood.
