### ISSUE TITLE
Tone portamento volume issue

### ISSUE THREAD

**Issue by Kabcorp** [SuperDisk/UGE#30]
Example:
Intrument 1 have a volume of 15
	
C-5 01 ...
... .. ...
C-5 01 C03
... .. ...
C-4 01 3A0  <-- here, the volume still at 03 instead of 0F.

Because an INStrument ID is set, the volume have to be reset (like XM/MOD)

**Comment by SuperDisk** [comment]
I think this should be fixed? I merged Toxa's change which I believe solves this. Please reopen if not.
