### ISSUE TITLE
Tone preview

### ISSUE THREAD

**Issue by Kabcorp** [SuperDisk/UGE#31]
-When "CTRL" is pressed on a note, preview the sound.
-When you whange the note, preview the sound.

(Like LSDj) It will give a hUGE advantage for placing notes quickly on keyboard.

**Comment by SuperDisk** [comment]
The changing note thing is implemented now, but I'm not sure about CTRL, it might need to be something else-- maybe ` or something? Otherwise it will be making sound when you're copying and pasting :P

**Comment by SuperDisk** [comment]
This is (for the most part) implemented in [e930310](https://github.com/SuperDisk/hUGETracker/commit/e9303108a1c35fe667a598d574fbad2580ee9f15). It does a single step of the row using <kbd>Enter</kbd> but you can press <kbd>Esc</kbd> and then <kbd>Enter</kbd> multiple times to get this effect. Please re-open if that isn't suitable.
