### ISSUE TITLE
Beta 4/5/6 not openning on windows 10

### ISSUE THREAD

**Issue by quentintamar** [SuperDisk/UGE#38]
Hi ! 
Like said in the title, i can open only the version below beta 3. 
The more recent Beta just doesn't open. its hard to describe it more, but first time windows asked me if i wanted to open it, 
i said yes, and since, nothing is happening when launching the .exe

Friends doesnt have issue with the same beta

Thanks !

**Comment by RichardULZ** [comment]
~~There is no 2.0beta6, but there is 2.0beta5 in the v2beta branch readme.~~ Ah, sorry, thought this was gbstudio 😅
Have you tried running as administrator? 
You could open task manager to see if any ~~electron~~ process is trying to open.

Any specs of the computer might help, and restarting the pc.
~~It doesn't sound like you're even getting an error message...~~

**Comment by SuperDisk** [comment]
Hmm, that's pretty curious. Is there a log file (`output.log`) being generated? If so, could you post that?

@RichardULZ are you thinking of GB Studio maybe? HT actually does have a beta 6 😋

**Comment by quentintamar** [comment]
its ok it worked after a few days, but couldn't find why ... probably my computer

**Comment by SuperDisk** [comment]
Good to hear! :)
