### ISSUE TITLE
crash: importing mod with lower note than C3

### ISSUE THREAD

**Issue by skarab** [SuperDisk/UGE#39]
When importing a mod containing notes under C3 it just crash.
(not a big deal for me I've just find/replace in openmt, but its an annoying bug i guess)

**Comment by SuperDisk** [comment]
Fixed in ebdb87b774ffc4ed26a068e42830997d928f6e73, thanks for reporting! I also [drafted a new release](https://github.com/SuperDisk/hUGETracker/releases) which should fix this issue, so go check it out :)
