### ISSUE TITLE
Shift click box selection in tracker (minor issue)

### ISSUE THREAD

**Issue by RichardULZ** [SuperDisk/UGE#4]
More polish, you can currently drag select a region in the tracker, or hold shift and use the arrow keys, but Shift clicking would be nice to have the same as drag box select, Standard in OpenMPT.

At first, it seems like just an accessibility feature, but if you have a small screen, being able to click, scroll, and shift click, lets you select more than you normally could by dragging.
Not major, but a nice to have.

**Comment by SuperDisk** [comment]
Implemented by 8c0850b. Multiple shift clicks have somewhat idiosyncratic behavior but maybe that won't be an issue.
