### ISSUE TITLE
exporting to gbs is broken (beta 8)

### ISSUE THREAD

**Issue by skarab** [SuperDisk/UGE#45]
Hello, got three errors while exporting song to .gbs :

rgbasm output:
ERROR/ hUGEDriver/gbs.asm (14) & (15) & (16)
Unterminated string

**Comment by SuperDisk** [comment]
Found the cause of this, it has to do with double quotes being in the song title/author field. Will fix asap.

**Comment by SuperDisk** [comment]
This is "fixed" in Beta 9, which just removes double quotes from the author/title fields. In the future I'll find a more robust solution, but this will work for now. Thanks for reporting!

**Comment by skarab** [comment]
awesome, thanks! :)
