### ISSUE TITLE
Font does not get loaded on first program launch

### ISSUE THREAD

**Issue by ISSOtm** [SuperDisk/UGE#48]
The way the pattern editor font is loaded is a bit of a hack, and fails the first time the program is ran.

We'll have to figure this out eventually, though it's arguably low priority for the time being.

**Comment by SuperDisk** [comment]
Note that this only applies to Linux, as on Windows the program uses a function which loads the font directly.

On Linux, the font is copied to a system fonts folder, which requires a restart of the program to begin working.
