### ISSUE TITLE
Copy and Paste Wave data as hex text string (Feature Idea)

### ISSUE THREAD

**Issue by RichardULZ** [SuperDisk/UGE#5]
BGB has a feature to investigate wave data currently in use, using the debugger's IO map,
![image](https://user-images.githubusercontent.com/34431457/77749419-dd5cda80-7086-11ea-8a80-af0480eddbe2.png)

Since wave channel is just 16 bytes, or rather, 32 x 4 bits, an easy to use text format might be a good alternative along side the import and export of UGw wavs.

This would also allow greater precision in editing waves as well as easier sharing.
![image](https://user-images.githubusercontent.com/34431457/77749480-fa91a900-7086-11ea-8a86-81c80267d97c.png)
2266AAEE FFFFFEEA A6668ACF FEECA633

What are your thoughts?

**Comment by SuperDisk** [comment]
I personally like the idea. However, one of the goals of the tracker is to be simple and unintimidating for musicians who otherwise know nothing about the Gameboy hardware, so I'm a little reluctant to have a big string of hex numbers displaying next to a graphically editable wave. The abstraction might have already leaked with a few of the effect codes though, so I'm still open to the idea.

Implemented in efea75403867dec2e3fd216989b6053d2c0850a6 to see how we end up liking it.

An alternative might be 2 buttons, for copying to clipboard and pasting from clipboard, which would just be this hex string for easy sharing without knowing anything about the hex.

**Comment by RichardULZ** [comment]
Working great! 
Neat to see it update live as you're drawing, and the play tone while drawing helps a lot.

As long as it's the same length (or longer), you can press enter to update, which is good, issues with too short length.
Some extra polish,
Not allowing invalid letters? Or cleaning them out when enter is pressed.
Extending to 32 bytes when too few characters are used and enter is pressed, possibly trim to 32 too.

A copy / paste menu would be good too, but it seems a shame to remove the textbox, it's a nice visual representation of what's happening alongside the graph editor, and although numbers are intimidating, this is the easiest possible way to learn what's going on, fantastic learning tool.


On the point of being intimidating, some better named starting preset instruments would go a long way. 

Such as the 3 square duty types 12.5, 25, 50, and same 3 duty types with an envelope.
Wave samples such as the 3 squares 12.5, 25, 50% (allows quick reusable tracks!) triangle, sine, sawtooth, others.
And noise presets with/without tone/envelope, although getting noise instruments in a linear scale would help more, everyone gets confused with only shift clock and dividing ratio.

**Comment by SuperDisk** [comment]
> On the point of being intimidating, some better named starting preset instruments would go a long way.

Rather than having them present at startup, what do you think about distributing a folder with some `.ugi` instruments that users can load?

**Comment by RichardULZ** [comment]
That might help, but the import process for many individual instuments seems slow.

I suppose gbt you always had to open a template file, but i was very confused when i first opened a tracker and it had no sounds to just get started with, learning instument creation first, and music second.

Will think about it.
Seems the new song button doesn't clear instruments so that might be helpful to keep?

The waves are always loaded with something already, so making those more useful to start off on editor load might be good.

**Comment by SuperDisk** [comment]
How about including a drag 'n drop feature for loading instruments? That is my typical workflow in Modplug for trying out a bunch of different samples as it's pretty fast.

**Comment by SuperDisk** [comment]
> Seems the new song button doesn't clear instruments so that might be helpful to keep?

This shouldn't be the case. What's being left over when you click the new button?

**Comment by SuperDisk** [comment]
I'm closing this specific issue since I think we solved it, but I created 2 new issues from the followup discussion (#17 and #18). Let me know if there's anything left unaddressed here!
