### ISSUE TITLE
Allow passing backup etc. dirs on the command-line

### ISSUE THREAD

**Issue by ISSOtm** [SuperDisk/UGE#51]
Currently, hUGETracker requires the directory it's in to be writable by whoever is running the program, for example to write backup files. This is okay if running hUGETracker "portably" (which is fine on Windows due to the pre-built distribution), but less so if doing a system-wide install (more typical on Linux via package managers).

The current packaging scheme I have is to put everything in `/opt`, and add a simple shell script in `/usr/bin` to run hUGETracker; it would pass the relevant CLI args to specify the user backup dir.

**Comment by SuperDisk** [comment]
How do most programs on Unix like systems handle this? Accepting paths via command line arguments seems a bit brittle to me.

**Comment by ISSOtm** [comment]
Usually via a compile-time "configure" switch, AFAIK.

**Comment by SuperDisk** [comment]
This should be implemented now in 695a203.
