### ISSUE TITLE
Tracker will not launch if working directory is not install directory

### ISSUE THREAD

**Issue by QuinnPainter** [SuperDisk/UGE#52]
For example, if I start the program from CMD in the install directory like ".\hUGETracker.exe" it works fine. But if I go up a folder, and run ".\hUGETracker_1_0b9\hUGETracker.exe", it does not work, saying it "can't load a required file which comes with the tracker". This also breaks launching the program from the Search part of the Windows start menu.

**Comment by SuperDisk** [comment]
Closed by 2c1c95a

Thanks for reporting!
