### ISSUE TITLE
Keyboard note preview cuts off when rolling notes

### ISSUE THREAD

**Issue by RichardULZ** [SuperDisk/UGE#57]
When pressing over multiple keys, the design cuts the sound for any key release, not the current (last) playing note key.

This is a seemingly minor issue that has a great impact on feel and polish.

Steps to reproduce
1. Select an instrument
2. Press and hold Z (hear note)
3. Press and hold X (hear new note)
4. Release Z (sound of X is stopped)

Ideas to solve,
Keep a value of the last pressed note key, and only check/compare if that is released to stop.
If there are other factors that make the note stop (eg defocus window, escape key) perhaps keep those, in case of a missed key release.

**Comment by SuperDisk** [comment]
Closed by #58
