### ISSUE TITLE
Test tone button on the wave drawing page (feature)

### ISSUE THREAD

**Issue by RichardULZ** [SuperDisk/UGE#6]
Would be nice to rapidly preview the wave being drawn without jumping tabs, 

Alternatively or additionally, Being able to play the instrument you are editing with the keyboard while in the instrument editors, but not in a text box? Another OpenMPT feature kinda.

![image](https://user-images.githubusercontent.com/34431457/77750611-f49cc780-7088-11ea-8315-12afd65eaabc.png)
![image](https://user-images.githubusercontent.com/34431457/77750628-febec600-7088-11ea-90a2-5c319ed194c3.png)

**Comment by SuperDisk** [comment]
Good idea. 5319254 implements a checkbox which allows you hear a wave as you're drawing it.

I considered implementing the OpenMPT style "press keys to test an instrument" thing but clicking out of a textbox just onto the form itself felt really unintuitive-- the "Test C-5" button was my "solution," although it seems it leaves something to be desired. Maybe a clickable visual piano widget would be better?
