### ISSUE TITLE
[Feature Request] Famitracker Style Instrument Macros or LSDJ Style Tables

### ISSUE THREAD

**Issue by darklink513** [SuperDisk/UGE#63]
It would be nice to see options that allow us to arbitrarily set arpeggios/exact pitch and duty cycle per tick like how Famitracker's instruments work. the existing envelope and defaults in the instrument settings are a great start, however I personally use complex techniques involving shifting around the duty cycle and pitch of the instrument. As it stands the only way to make this work in hUGE Tracker is to write the track at 1 tick per row placing each note and command in the pattern each time, which can be tedious and create complex timing as well as bloat in the pattern list. 

Having an option that allows us to set the pitch of the instrument relative to the placed note and duty cycle per tick like Famitracker's intruments or LSDJ's Tables would make this a lot easier and far cleaner to work with.

An example is a simple kick drum, taking the note from +12 half-steps above the placed note and over the course of 5 ticks dropping it to -12 half-steps below in a parabolic pattern can make a nice punchy kick. This isn't possible with the current implementation of instruments, only being possible by writing the track at 1 Tick per Row and placing the whole set of commands each time. Another example is creating a guitar strumming sound by changing the Duty Cycle from 12.5% to 50% over 3 ticks. This also is not possible without writing the track at 1 Tick per Row and placing each command every time they are used. 

Below are examples of both the instruments I am referring to.

![image](https://user-images.githubusercontent.com/35592696/145782001-50c81a99-160d-4a66-b7e0-3866349cc53b.png)

![image](https://user-images.githubusercontent.com/35592696/145782255-290de558-da86-4175-9772-90941e4014b5.png)

**Comment by SuperDisk** [comment]
Hey @darklink513, thanks for the issue! This is definitely something that is in the to-do list. Will update this issue when I make some progress.

**Comment by SuperDisk** [comment]
This is (finally) implemented since c38f1f39c19653dffb8f35e438f3189a713c5575, in the form of subpatterns. I'm working towards a new release which will include this functionality, but in the meantime you can grab a build out of the Github Actions and mess around with it if you want (although beware that it's not fully documented yet).
