### ISSUE TITLE
build on raspberry pi4 (raspberry os 32bit)

### ISSUE THREAD

**Issue by jackygoule** [SuperDisk/UGE#67]
Hello i test to build HT on raspberry pi4 raspberry  os 32bit but i think that line won't work

:: Let Lazarus know about the dependencies that HT uses
lazbuild --add-package-link rackctls/RackCtlsPkg.lpk
lazbuild --add-package-link bgrabitmap/bgrabitmap/bgrabitmappack.lpk

I test build and i have this errors :
16.609] Executing "/usr/bin/ld.bfd" with command line "  --dynamic-linker=/lib/ld-linux-armhf.so.3  --gc-sections -s  -L. -o /home/pi/hUGETracker/Release/hUGETracker -T /home/pi/hUGETracker/Release/link.res -e _start"
[17.461] /home/pi/hUGETracker/hUGETracker.lpr(87,1) Error: (9013) Error while linking
[17.461] /home/pi/hUGETracker/hUGETracker.lpr(87,1) Fatal: (10026) There were 1 errors compiling module, stopping
[17.500] Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcarm returned an error exitcode
Error: (lazarus) Compilation du projet - Mode : Production Linux - Cible : Release/hUGETracker : stopped with exit code 1
Error: (lazbuild) failed compiling of project /home/pi/hUGETracker/hUGETracker.lpi

If a 32bits version for windows exsit i can run HT with wine.
Thanks for your job.

**Comment by SuperDisk** [comment]
I don't think there's anything technically preventing HT from compiling on a Raspberry Pi, but the default build settings are for x86-64 Windows, Mac and Linux. You'll have to open up the `.lpi` file in Lazarus and change the architecture to whatever your Raspberry Pi is. You could also just build using 32-bit Lazarus on Windows and run under Wine, like you mentioned.

**Comment by jackygoule** [comment]
Hello in .lazarus i find 2 files :
environmentoptions.xml  and packagefiles.xml
I don't know what i have to modify for build on 32bit arm.

**Comment by SuperDisk** [comment]
@jackygoule I don't think you need to edit any files that are part of Lazarus. If you open `hUGETracker.lpi` in Lazarus itself, then hit `Run -> Compile`, you should at least get a compiled binary. Be sure you also have `SDL2` installed on your system (with `apt` probably).

If you're running into problems, I'd be happy to help on a Discord call or something, just send me a message.

**Comment by jackygoule** [comment]
hello i open hUGETracker.lpi and i compile with succes.
When i try to execut i have a error windows:
hUGETracker can't load a required file which comes with the tracker. This likely means that you haven't extracted the program before running it. Please do so, and relaunch. Thanks!
When i start with terminal :
pi@fabien:~/hUGETracker $ ./hUGETracker 
[ERROR] Couldn't load Pixelite!!!

(hUGETracker:5588): Gtk-CRITICAL **: 18:13:53.018: IA__gtk_widget_realize: assertion 'GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
Exception at 000C9E10: EInOutError:
File not found.
[TGtk2WidgetSet.Destroy] WARNING: There are 1 unreleased DCs, a detailed dump follows:
[TGtk2WidgetSet.Destroy]  DCs:   B4919FC0
[TGtk2WidgetSet.Destroy] WARNING: There are 9 unreleased GDIObjects, a detailed dump follows:
[TGtk2WidgetSet.Destroy]   GDIOs: 923BC1E0 923BC0C0 B4DD80C0 923BC060 923BC000 923BBF40 923BBEE0
[TGtk2WidgetSet.Destroy]   gdiBitmap: 3
[TGtk2WidgetSet.Destroy]   gdiBrush: 2
[TGtk2WidgetSet.Destroy]   gdiFont: 2
[TGtk2WidgetSet.Destroy]   gdiPen: 2

Thanks for your help

**Comment by jackygoule** [comment]
i find a file PixeliteTTF.ttf in hUGETracker.zip 
Now when i try with terminal
(hUGETracker:9981): Gtk-CRITICAL **: 18:37:49.775: IA__gtk_widget_realize: assertion 'GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
Exception at 000C9E10: EInOutError:
File not found.
[TGtk2WidgetSet.Destroy] WARNING: There are 1 unreleased DCs, a detailed dump follows:
[TGtk2WidgetSet.Destroy]  DCs:   B4950FC0
[TGtk2WidgetSet.Destroy] WARNING: There are 9 unreleased GDIObjects, a detailed dump follows:
[TGtk2WidgetSet.Destroy]   GDIOs: B302BE20 B302C060 B302BF40 B302C0C0 B302C120 B302C000 B4E0F0C0
[TGtk2WidgetSet.Destroy]   gdiBitmap: 3
[TGtk2WidgetSet.Destroy]   gdiBrush: 2
[TGtk2WidgetSet.Destroy]   gdiFont: 2
[TGtk2WidgetSet.Destroy]   gdiPen: 2

I see very quick hUGETracker and stop 
Thanks

**Comment by SuperDisk** [comment]
Hi, in order to use hUGETracker you need the following files:

`PixeliteTTF.ttf`, `halt.gb`, `halt.sym`, and `hUGEDriver`.

You can either build `halt.gb` and `halt.sym` yourself, or just grab them out of the release `.zip`. The `hUGEDriver` directory should be in the root of the git repo if you cloned recursively.

**Comment by SuperDisk** [comment]
@jackygoule Let me know if this also ends up working on the raspberry pi too, since you successfully built and ran on Debian. (#76)

**Comment by jackygoule** [comment]
Hello in a folder i put the HT's binary i build and extract the files in hUGETracker.zip  in the same folder and HT run .
I not use a lot of for today but i see the vu-metre on the top are very slow .
I use HT on my pi4 (4go)  more time and i will  see if it's good.

I put a zip file with  all files to run HT on pi4 with raspberry os 32bits ,very easy to install with it : extract and run HT
Thanks  for your help
[HT-pi4.zip](https://github.com/SuperDisk/hUGETracker/files/8404816/HT-pi4.zip)
