### ISSUE TITLE
Inserting tracker notes should use channel specific instruments (feature)

### ISSUE THREAD

**Issue by RichardULZ** [SuperDisk/UGE#7]
Now that we have 15 dedicated instruments for all 3 channel types, typing them should be a lot easier.
![image](https://user-images.githubusercontent.com/34431457/77838175-e906e900-71cd-11ea-83d0-7cdfa837386f.png)

**1. Active instrument should be **instrument 1** when editor starts.**
Currently (no instument), might reduce confusion for new users expecting a sound to play.

**2. Switch instrument based on channel being written to**
When inserting `square 1` on the `Wave` or `Noise` channel, it should instead **switch** to that **channels instrument type**, as `Wave 1` or `Noise 1`. 
This was a fair complaint from GBT users who were confused when they tried square sounds on ch4, now that song playback is accurate here, it's more for those who wished it could auto switch based on selected channel.

Either change active instrument on `typing` a note into the tracker, or when `clicking/moving` in the tracker patterns.
Swap with the `same instrument number`, or `last used` instrument per channel (last used could be harder to test for bugs, might not be worth it).
When using `(no instrument)`, dont change between channels.

**3. Squares should play on ch1 or ch2, as some effects are exclusive to ch1**
As an addendum, Squares should play on the selected channel in tracker, as the `instrument sweeps` are only available on ch1, typing in ch2 should not preview them
(Double check Test C-5 will still play on channel 1 for squares, even if you last previewed a note on ch2.)

Hope it's not too much to ask, and any thoughts are welcome.

**Comment by SuperDisk** [comment]
Implemented in 8ee5b1dc44e157122100189d32e26a0778178834.

I think the default instrument should still start on (no instrument) but please elaborate if you disagree, I'm open to changing it.

**Comment by RichardULZ** [comment]
Still thinking we should make the default instrument start on 1, i spent about 10 minutes trying to figure that one out until i questioned you on discord, thought it was just a missing feature 😆

@deertears also couldn't figure out what/where it was for a few minutes when they opened it up.
