### ISSUE TITLE
[UI Request] Instrument selection methods

### ISSUE THREAD

**Issue by Pegmode** [SuperDisk/UGE#70]
I'd suggest having the ability to more quickly select an instrument.

The current drop down menu method can be quite tedious since you have to first open the drop down menu, then scan this new menu for your instrument and finally click the entry. I suggest having the option to make it so that when you have an instrument selected in the list on the left hand side (pictured), that instrument is automatically selected. Most trackers have this same workflow. 

The reasoning is that you are likely to want to place the instrument that you are currently editing. I suggest adding the option to toggle this behavior since some people might be thrown off by this behavior.

![ht_instrument_select](https://user-images.githubusercontent.com/738053/152836480-8a7affee-e60b-41ba-adf5-f6c7090a95d5.png)

**Comment by SuperDisk** [comment]
Implemented in 308612ad5b57f02e19c34acec9f70b012cc4ddd7. Thanks for the suggestion!
