### ISSUE TITLE
[UI Request] Hex Pattern number toggle

### ISSUE THREAD

**Issue by Pegmode** [SuperDisk/UGE#71]
I'd suggest having the ability to change the pattern row number display (see image) to hexadecimal similar to how there is a toggle option for row number inside a pattern. 

For example this makes `Bxx` command parameters easier to write since you don't have to convert them first.

![ht_pattern_matrix](https://user-images.githubusercontent.com/738053/152837761-9fc5bf4d-2f06-4395-8fb8-f65c073523f7.png)

**Comment by SuperDisk** [comment]
Implemented in 067c11b168f512dda001a65ff10ee6188ba280d7. Thanks!
