### ISSUE TITLE
[Input request] Add "Paste Mix"

### ISSUE THREAD

**Issue by Pegmode** [SuperDisk/UGE#72]
Add the ability to "Paste Mix". This feature is found in many trackers such as Deflemask (ctl+b) or Famitracker (ctl+m).

Paste mix pastes the pattern data in your clipboard but importantly: if  the position in your clipboard contains an empty value, then it does not overwrite whatever is currently at that position in the pattern.

Example with screenshots from hUGETracker:

we start with this in our pattern. This is also we copy to our clipboard for simplicity.
![ht_b_init](https://user-images.githubusercontent.com/738053/152839529-7ee455aa-f569-4cba-85ef-f85cc1f6f72d.png)

if you perform a normal paste in row 2 this is what happens.
![ht_b_bad](https://user-images.githubusercontent.com/738053/152839814-5d7198c3-4e70-4a25-b0e7-2d139d9ddf47.png)

If you were to perform a paste-mix in this position with the same content this is what you would be pasted
![ht_b_paste_mix](https://user-images.githubusercontent.com/738053/152839935-02ef7f27-edaf-4257-9ee6-17a5339fe61a.png)

Paste mixing is used commonly for "meta effects" in trackers and greatly speeds up workflow.

**Comment by SuperDisk** [comment]
Implemented in 5468cabe97d35ee5940e0ce1014663f1d1d8add5 with hotkey `Ctrl+Shift+V` (like in OpenMPT). Thanks!
