### ISSUE TITLE
Mac Version Request

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#73]
I would like to use this but I have a Mac computer

**Comment by RichardULZ** [comment]
https://github.com/SuperDisk/hUGETracker/issues/36#issuecomment-1036975104
 https://github.com/SuperDisk/hUGETracker/actions

**Comment by SuperDisk** [comment]
Thanks @RichardULZ! It's worth noting that the Mac build is currently not very performant due to MacOS's extremely slow text drawing routines. It's on the to-do list to find a way to optimize this on Mac.
