### ISSUE TITLE
[UI Request] Add an input step feature

### ISSUE THREAD

**Issue by Pegmode** [SuperDisk/UGE#74]
I suggest adding an easily reachable value in the main interface that can be incremented/decremented called "input step". This value determines how many rows in the pattern editor the cursor will advance by when inputting a note/effect/instrument.

Step value n will move the cursor n rows ahead when placing a value.

eg:
Step value 0 will keep the current behavior where the selected position remains the same after input. 
Step value 1 will advance to the next row when a note/instrument/effect is placed.
Step value 2 will do the same but to 2 rows ahead. 
...etc

This would speed up workflow greatly since someone wouldn't have to move the cursor after every note input.

**Comment by SuperDisk** [comment]
I think what you're asking for is already implemented-- is this what you're talking about?

![image](https://user-images.githubusercontent.com/1688837/155051115-8a1d7725-fd21-4248-83f4-03b2374ebf4d.png)

**Comment by Pegmode** [comment]
Ah damn yeah that should be it
