### ISSUE TITLE
Don't start after build on debian 11

### ISSUE THREAD

**Issue by jackygoule** [SuperDisk/UGE#76]
Hello i build with no error and HT don't start 

 ./hUGETracker 
Gtk-Message: 08:26:48.163: Failed to load module "canberra-gtk-module"
[ERROR] Couldn't load Pixelite!!!

(hUGETracker:14759): Gtk-CRITICAL **: 08:26:55.504: IA__gtk_widget_realize: assertion 'GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
[TGtk2WidgetSet.Destroy] WARNING: There are 1 unreleased DCs, a detailed dump follows:
[TGtk2WidgetSet.Destroy]  DCs:   00007FC8BAE9EC40
[TGtk2WidgetSet.Destroy] WARNING: There are 9 unreleased GDIObjects, a detailed dump follows:
[TGtk2WidgetSet.Destroy]   GDIOs: 00007FC8BAB3C340 00007FC8BAB3C240 00007FC8BAB3C6C0 00007FC8BAB3C3C0 00007FC8BAB3C440 00007FC8BAB3C4C0 00007FC8BE3E6DC0
[TGtk2WidgetSet.Destroy]   gdiBitmap: 3
[TGtk2WidgetSet.Destroy]   gdiBrush: 2
[TGtk2WidgetSet.Destroy]   gdiFont: 2
[TGtk2WidgetSet.Destroy]   gdiPen: 2

I install sudo apt install libcanberra-gtk-module libcanberra-gtk3-module
and now when i try :

./hUGETracker 
[ERROR] Couldn't load Pixelite!!!

(hUGETracker:14898): Gtk-CRITICAL **: 08:28:21.829: IA__gtk_widget_realize: assertion 'GTK_WIDGET_ANCHORED (widget) || GTK_IS_INVISIBLE (widget)' failed
[TGtk2WidgetSet.Destroy] WARNING: There are 1 unreleased DCs, a detailed dump follows:
[TGtk2WidgetSet.Destroy]  DCs:   00007F50AF744C40
[TGtk2WidgetSet.Destroy] WARNING: There are 9 unreleased GDIObjects, a detailed dump follows:
[TGtk2WidgetSet.Destroy]   GDIOs: 00007F50B2CE0DC0 00007F50AF3E2340 00007F50AF3E23C0 00007F50AF3E2240 00007F50AF3E2440 00007F50AF3E24C0 00007F50AF3E26C0
[TGtk2WidgetSet.Destroy]   gdiBitmap: 3
[TGtk2WidgetSet.Destroy]   gdiBrush: 2
[TGtk2WidgetSet.Destroy]   gdiFont: 2
[TGtk2WidgetSet.Destroy]   gdiPen: 2

Thanks for your help

**Comment by SuperDisk** [comment]
Follow these steps and let me know if it still doesn't work: https://github.com/SuperDisk/hUGETracker/issues/67#issuecomment-1065928551

**Comment by jackygoule** [comment]
Hello ,
After extract from .zip  and copy   PixeliteTTF.ttf, halt.gb, halt.sym, and hUGEDriver in the release folder's build
HT run .
Thanks
