### ISSUE TITLE
Crash and Corrupted File

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#78]
While I was working on a song, Huge crashed. It said it backed up the file but the file is apparently corrupted because Huge will no longer open it and crashes when it tries to play it

The crash error: 
<img width="388" alt="Screen Shot 2022-08-03 at 4 28 50 PM" src="https://user-images.githubusercontent.com/57502156/182730554-8255ef67-803f-4f8b-913e-ab6f9e398dfc.png">

The errors opening the file:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/57502156/182730612-dbf33468-4eb0-4a3f-a9bb-70a2ae16484d.png">
(of course I extracted it)

Error when trying to play the song:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/57502156/182730677-2c0b40a8-2588-4537-9b4b-9d034536200e.png">

**Comment by SuperDisk** [comment]
Hi, could you attach the module file?

**Comment by maxoakland** [comment]
> Hi, could you attach the module file?

Here you go
[Akira Track 01-2.uge.zip](https://github.com/SuperDisk/hUGETracker/files/9262969/Akira.Track.01-2.uge.zip)

**Comment by SuperDisk** [comment]
The song isn't actually corrupted, it's just that you've somehow inserted some invalid notes into it. How did you make this song? Was it imported from somewhere, or copy/pasted from OpenMPT, or something? If you scroll through the song, you'll see a few places where there's `???` in place of a note-- that's an invalid note code.

If you remove these, then the song will be valid again, but it's then it's too big to fit in one bank since there's a huge amount of unique patterns.

**Comment by maxoakland** [comment]
> 



> The song isn't actually corrupted, it's just that you've somehow inserted some invalid notes into it. How did you make this song? Was it imported from somewhere, or copy/pasted from OpenMPT, or something? If you scroll through the song, you'll see a few places where there's `???` in place of a note-- that's an invalid note code.
> 
> If you remove these, then the song will be valid again, but it's then it's too big to fit in one bank since there's a huge amount of unique patterns.

This is the track I was copying and pasting from Famitracker

After some very slow searching I see the ???. Can you make it so they turn up red? I found it really hard to see them because they’re so close to the background color

Also the warning that comes up should be more descriptive and probably shouldn’t crash the application if you can help it

Also, thanks for taking a look at this. I’ve gone over the whole file several times but it’s still not playing even though all the ? marks are gone

**Comment by SuperDisk** [comment]
I added a safety guard in [07f720a](https://github.com/SuperDisk/hUGETracker/commit/07f720ac18d251f86e2a6ec6c2e6fd1c299e8470) which clamps any FamiTracker note to a valid range, so at minimum there shouldn't be any more `???` appearing.
