### ISSUE TITLE
Tracker undo buffer, not tracking patterns, weird first state undo (Bug)

### ISSUE THREAD

**Issue by RichardULZ** [SuperDisk/UGE#8]
**The undo buffer has a few problems,** 

Gif shows **Changing channel pattern numbers is not recorded**/undo able, and then changing notes in the tracker and undoing to first state can cause strange effects.
![UndoBufferBugs](https://user-images.githubusercontent.com/34431457/77846363-0e1d4b00-7212-11ea-8c89-a4becc15bd4d.gif)
So bug 1, pattern changes are not undoable.

**2, Undo buffer first state bugs**
On a blank project, add 2-3 notes, then undo them, when you undo the 1st note you placed, it fills the screen with C-3

On a blank project, add 1 note, add an instrument number, then add another note, undoing back to the first operation may appear to redo, or mess up with C-3.

**More refined test of same bug.**
Load a project, add 1 note with or without instrument assigned, try to undo, will have no effect. 
Add 1 more note after trying to undo, and undo will again have no effect.
Add 2 notes and undo will work once, then "redo" kinda.
Add 3 notes, and undo will work twice, then cause a mess of c-3 everywhere, changing patterns will update the view and show the mess is only on pattern 0, but has ruined it, and is not undoable/redoable.

**Comment by SuperDisk** [comment]
This happens due to a fundamental problem in the way patterns are loaded into the tracker view. When loading a new order, the previous changes aren't "checkpointed" so this creates a problem where new edits on an order get erased from history when undoing, and at the very beginning there's sort of a weird corruption (the C-3s). I'll look into fixing this asap.

**Comment by SuperDisk** [comment]
This should be fixed now! (although it does take double the RAM to store the before and after patterns, oh well.)
