### ISSUE TITLE
macOS build: Pattern view not using correct font

### ISSUE THREAD

**Issue by sttng** [SuperDisk/UGE#81]
At least the pattern view is not using the correct font, and as such the Pattern Editor becomes virtually unusable on macOS.

<img width="1440" alt="Screen Shot 2022-08-27 at 12 51 01 PM" src="https://user-images.githubusercontent.com/46765778/187015029-ef9448ee-f3f3-4fe9-aa88-016840f7bb5d.png">

I have the following output in terminal if it helps:

Last login: Sat Aug 27 12:47:43 on ttys005
m2m@M2ms-MacBook-Pro ~ % /Users/m2m/Downloads/Mac\ build/hUGETracker ; exit;
StretchMaskBlt Error - invalid source device context TCocoaContext, expected TCocoaBitmapContext!
StretchMaskBlt Error - invalid source device context TCocoaContext, expected TCocoaBitmapContext!
StretchMaskBlt Error - invalid source device context TCocoaContext, expected TCocoaBitmapContext!
StretchMaskBlt Error - invalid source device context TCocoaContext, expected TCocoaBitmapContext!
StretchMaskBlt Error - invalid source device context TCocoaContext, expected TCocoaBitmapContext!

**Comment by SuperDisk** [comment]
On macOS you need to manually install the font `PixeliteTTF.ttf` that comes with the tracker.

**Comment by sttng** [comment]
> On macOS you need to manually install the font `PixeliteTTF.ttf` that comes with the tracker.

Confirming installing the `PixeliteTTF.ttf` font fixes the issue.
<img width="1319" alt="Screen Shot 2022-08-27 at 1 07 56 PM" src="https://user-images.githubusercontent.com/46765778/187015598-56e82a3e-692e-4e91-a8bb-aca32a88647c.png">

**Comment by SuperDisk** [comment]
Note though that the tracker's UI repainting is still really slow on macOS, so it's going to likely be unusable either way.

**Comment by sttng** [comment]
I see. I think the UI has a couple of issues on macOS. I'll create a separate issue and list things i found.

**Comment by SuperDisk** [comment]
Sure thing, that would be highly appreciated.
