### ISSUE TITLE
Nonstandard Behavior: Undo and Redo Menu

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#84]
I've been using hUGETracker for a few months and find myself very vexed by the several instances of nonstandard behavior. I'm reporting them here because fixing this will make the application a lot easier to use for everyone. Even just because of the muscle memory of every other application working a certain way, it makes it easier to transfer those skills without thinking into hUGETracker

In other applications, Undo and Redo appear at the top of the Edit menu. They are in an unusual place in hUGETracker

**Comment by SuperDisk** [comment]
Just implemented this as of [68d79e3](https://github.com/SuperDisk/hUGETracker/commit/68d79e3376c927e6d8d36a837ca8633092f278ed). Thanks!
