### ISSUE TITLE
Feature Request: Revert Menu

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#85]
Lots of applications I use on a daily basis have a **Revert to Saved** option in the file menu. This undoes all changes and reloads the saved version of a file

**Comment by SuperDisk** [comment]
Good idea, I'll implement this.

**Comment by SuperDisk** [comment]
Implemented in [710dab7](https://github.com/SuperDisk/hUGETracker/commit/710dab7d816784a2fb87e0265170455b44c6d273).
