### ISSUE TITLE
Feature Request: Mouse Scroll Wheel Speed Options

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#86]
Even with the lowest setting in Windows, the mouse scroll speed is so fast it's unusable. Being able to turn mouse scrolling off or change the speed would be really helpful to me. Right now, any time I accidentally hit the mouse scroll wheel, the view shoots off to somewhere I don't want to be

**Comment by SuperDisk** [comment]
That's odd, I don't have any problems with it, it moves a reasonable amount on my machine. I've also found this to be the case on other computers. Maybe it's some sort of system setting or weird mouse wheel?

**Comment by maxoakland** [comment]
> That's odd, I don't have any problems with it, it moves a reasonable amount on my machine. I've also found this to be the case on other computers. Maybe it's some sort of system setting or weird mouse wheel?

Probably. I’m using this in Windows 7 through virtualization on Mac OS. Unfortunately there’s no option to make the mouse wheel move slower than I already set it

**Comment by SuperDisk** [comment]
I think this is some sort of virtualization bug rather than something I have the capability to fix. Please re-open if you experience the issue outside of a VM.
