### ISSUE TITLE
Feature Request: Link to Documentation from Help Menu

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#87]
Right now, there's no easy way to access the documentation from the Help menu. This is the purpose of the help menu so I think it will be important to add it

**Comment by SuperDisk** [comment]
Good idea, will implement. Should there just be a button to open the manual? Originally I planned to make it such that any component could be clicked and it would open the manual directly to that section, but it seems like it's too difficult or platform-dependent and fiddly to make work well.

**Comment by maxoakland** [comment]
> Good idea, will implement. Should there just be a button to open the manual? Originally I planned to make it such that any component could be clicked and it would open the manual directly to that section, but it seems like it's too difficult or platform-dependent and fiddly to make work well.

That’s an awesome idea and I think it could be great. Maybe you can find a way to do it in a platform independent way

A button is a nice idea but the help menu is where all my other applications have their documentation accessible so I’d say do both or menu

**Comment by SuperDisk** [comment]
Implemented in 8d82839fb8e5693549209b37548c5b354f9ba4e0, right now it opens the WIP manual hosted by @ISSOtm, although this should be changed whenever the manual is complete and hosted elsewhere.
