### ISSUE TITLE
Nonstandard Behavior: Right Click Menu

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#88]
_I've been using hUGETracker for a few months and often get frustrated by several instances of nonstandard behavior. I'm reporting them here because fixing this will make the application a lot easier to use. Even just because of the muscle memory of every other application working a certain way, it makes it easier to transfer those skills without thinking into hUGETracker_

Many options that should be in the Edit menu only appear in the right click menu. These include:
- Select All
- Select Channel
- Transpose Options
- Interpolate Options
- Flood Paste
- Erase
- Edit Effect

**Comment by SuperDisk** [comment]
These are going to stay in just the right click menu, most likely.

**Comment by maxoakland** [comment]
> These are going to stay in just the right click menu, most likely.

Is there a reason for that? It’s harder to use software when options are hidden behind contextual menus

**Comment by SuperDisk** [comment]
The Edit menu is a global thing, not specific to the tracker grid, so what should it do when you do "flood paste" while in the instruments screen? I guess those options could be greyed out there, but I don't really like that solution-- FWIW, OpenMPT does the same thing here and just leaves the basic stuff in the Edit menu and most actions are in the right click on the pattern grid. Sorry, I have to close this one and leave it as it is. Thanks for the suggestion though.

**Comment by maxoakland** [comment]
> so what should it do when you do "flood paste" while in the instruments screen? I guess those options could be greyed out there

That's the standard behavior in all operating systems I've used
