### ISSUE TITLE
Confusing Behavior: Right Click on Channel Title

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#89]
Right clicking on the channel title with speaker icons disables every other channel. This is not the behavior I expected. I expected a menu to come up. In the menu there could be an option to disable other channels. Either way, there should be some way to easily undo that too by right clicking again or a menu that says Enable All Channels

**Comment by SuperDisk** [comment]
Yes, this is a good idea-- I probably won't make a menu appear, but rather make it so that:

* Right click on enabled channel = Solo that channel
* Right click on enabled channel and all others are muted = Unmute all channels

**Comment by maxoakland** [comment]
> Yes, this is a good idea-- I probably won't make a menu appear, but rather make it so that:
> 
> * Right click on enabled channel = Solo that channel
> * Right click on enabled channel and all others are muted = Unmute all channels

That would be an improvement

**Comment by SuperDisk** [comment]
The behavior I described is now implemented in [fab29aa](https://github.com/SuperDisk/hUGETracker/commit/fab29aaef1c96c69c13171baeb4f83e2e414b73f).
