### ISSUE TITLE
Feature Request: Wave Grid

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#91]
When using the Wave editor, it seems like there's a horizontal grid but since it's not visible, it's hard to use the Wave editor.

Creating some subtle lines that show where the changes can be made would make this tool a lot easier to use

**Comment by SuperDisk** [comment]
This is another OpenMPTism.

![image](https://user-images.githubusercontent.com/1688837/188252993-7b44aca3-6896-48d1-85e0-703023a66879.png)

Although they do have vertical marking bars on the envelope editor:

![image](https://user-images.githubusercontent.com/1688837/188253009-6c6de9fd-ec01-46aa-bc08-fdebe7b85871.png)

So I could potentially implement something like that.

**Comment by maxoakland** [comment]
I definitely think you should. OpenMPT might not have that feature but that doesn’t mean it wouldn’t be a useful feature

**Comment by SuperDisk** [comment]
Implemented in bad74d463a14afb5724742f33f278387f7392ebb, thanks!
