### ISSUE TITLE
Feature Request: Wave Editor Test Button

### ISSUE THREAD

**Issue by maxoakland** [SuperDisk/UGE#92]
Using the Wave Editor, I would like to be able to easily test the wave without switching to the instrument page

Also a continuous test option would be great so I can hear the wave change every time I make a change to it

**Comment by SuperDisk** [comment]
![image](https://user-images.githubusercontent.com/1688837/195963687-024cf226-1ff1-4f96-be05-d6d9e4e6cb61.png)
This is already implemented, just use `Play wave while drawing`.
