### ISSUE TITLE
New feature: Sound effects for use with GBDK/GBStudio

### ISSUE THREAD

**Issue by ghost** [SuperDisk/UGE#93]
Hi,

This is probably not the right place to talk about this as it's specifically for GBDK/GBS, but I've been thinking about adding the ability to play sound effects as a music track is playing in a .GB ROM. GBStudio for example supports playing some very, very basic sound effects but that's about it. This could be changed by expanding the hUGEDriver code.

The way I was thinking is to have a separate kind of exported .c / .uge file, which describes a sound effect. It would essentially look like a music file, but only 1 pattern in size (assuming no one would need sound effects longer than that), and with markers on each channel signifying when a sound on that channel starts/ends, so that the music can get muted on that channel for the duration of it.

I'm willing to work on this feature myself, but I was just wondering if such a feature would be considered useful in a future hUGETracker release.

Best regards

**Comment by SuperDisk** [comment]
Hey, thanks for the suggestion. I don't know if you're aware, but GB Studio just recently released a new update which overhauled the sound effect system. It now supports [FX Hammer/CBT-FX](https://github.com/datguywitha3ds/CBT-FX) and [VGM2GBSFX](https://github.com/untoxa/VGM2GBSFX), which means you can do much more sophisticated sound effects using those. In fact, hUGETracker's unreleased new version can export VGM, which means you can create VGM files that can play as sound effects in GB Studio, which means writing new code to do SFX as part of HT itself isn't necessary.

Let me know if those solutions work for you.

**Comment by SuperDisk** [comment]
Given that VGM2GBSFX (I think) addresses this issue, I'm going to close for now. Please re-open if you don't think it fits your needs.
