### ISSUE TITLE
Bug: Dxx Pattern Break Command not working with D00 ? 

### ISSUE THREAD

**Issue by sttng** [SuperDisk/UGE#98]
I'm using the latest build (#150 ? ) from here: https://github.com/SuperDisk/hUGETracker/actions/runs/3148195528
It seems the Dxx command is broken with D00. D01 (and other values i tried seem to work). No sure if the Jump is "off" by 1 (thats what I assume however).

**Comment by SuperDisk** [comment]
The jump is indeed off by one, so `D01` jumps to the first row of the next pattern.

I know it's a little weird, sorry :P

**Comment by sttng** [comment]
Might update the manual ;) 
Thanks for confirming !
