### ISSUE TITLE
Error in Testing Octave of a Wave instrument

### ISSUE THREAD

**Issue by sttng** [SuperDisk/UGE#99]
I' m getting the attached Error Windows popping up when using the test octave button. This only affects one song of mine (attached). The song still plays fine.

Latest commit version of hUGETracker.

Screenshot:
![Error Capture](https://user-images.githubusercontent.com/46765778/193732772-23865bc9-679c-4333-9067-dc7d8b97fcf0.PNG)

Song:
[Konami Logo.zip](https://github.com/SuperDisk/hUGETracker/files/9702711/Konami.Logo.zip)

**Comment by SuperDisk** [comment]
This error happens when a preview button is pressed and the song is currently playing (I think). Or somehow you got into a state where `halt.gb` wasn't loaded-- I'll look into this generally and try to prevent that state from happening.

**Comment by SuperDisk** [comment]
Fixed in [a7779ed](https://github.com/SuperDisk/hUGETracker/commit/a7779eda4ae7d424e90f41d9902de23c7a23df11).
